name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Set up environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8  
      - name: Build, Test and Publish package (.war file) to GitHub
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
      - name: Deploy .war binary to a Tomcat in Amazon EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "/target/petclinic.war"
          target: "/home/fernando"
